# Generated by Django 5.2.3 on 2025-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('shrink_image', models.ImageField(blank=True, null=True, upload_to='shrinks/')),
                ('bulge_image', models.ImageField(blank=True, null=True, upload_to='bulges/')),
                ('asym_mask', models.ImageField(blank=True, null=True, upload_to='asym_masks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
